---
- name: Create VPC for Jenkins
  ec2_vpc_net:
    state: present
    region: "{{ variables.aws_region }}"
    name: "{{ variables.vpc_name }}"
    cidr_block: "{{ variables.cidr_block }}"
    dns_hostnames: yes
    dns_support: yes
    multi_ok: no
    tenancy: default
    profile: "{{ variables.profile }}"
    tags:
      Name: jenkins_vpc
  register: jenkins_vpc

- name: Create subnets
  ec2_vpc_subnet:
    state: present
    profile: "{{ variables.profile }}"
    region: "{{ variables.aws_region }}"
    az: "{{ variables.aws_region }}b"
    vpc_id: "{{ jenkins_vpc.vpc.id }}"
    cidr: "{{ item.value.cidr }}"
    tags:
      Name: "jenkins_{{ variables.aws_region }}b"
  with_dict: "{{ variables.vpc_subnets }}"
  register: jenkins_vpc_subnets


- name: Create Internet Gateway
  ec2_vpc_igw:
    state: present
    profile: "{{ variables.profile }}"
    region: "{{ variables.aws_region }}"
    vpc_id: "{{ jenkins_vpc.vpc.id }}"
    tags:
      Name: "jenkins_igw"
  register: jenkins_igw


- name: Grab the route tables
  ec2_vpc_route_table_info:
    profile: "{{ variables.profile }}"
    region: "{{ variables.aws_region }}"
    filters:
      vpc-id: "{{ jenkins_vpc.vpc.id }}"
  register: jenkins_route_table_info


- name: Update the route table in the vpc
  ec2_vpc_route_table:
    state: present
    lookup: id
    route_table_id: "{{ jenkins_route_table_info.route_tables[0].id }}"
    vpc_id: "{{ jenkins_vpc.vpc.id }}"
    profile: "{{ variables.profile }}"
    region: "{{ variables.aws_region }}"
    tags:
      Name: "jenkins_route_table_{{ jenkins_vpc.vpc.id }}"
    subnets:
        - "{{ item.subnet.id }}"
        # - "{{ jenkins_vpc_subnets.results[1].subnet.id }}"
    routes:
      - dest: 0.0.0.0/0
        gateway_id: "{{ jenkins_igw.gateway_id }}"
  with_items: "{{ jenkins_vpc_subnets.results }}"
  register: jenkins_route_table_updated



- name: "Create vpc security groups"
  ec2_group:
    state: present
    profile: "{{ variables.profile }}"
    region: "{{ variables.aws_region }}"
    vpc_id: "{{ jenkins_vpc.vpc.id }}"
    name: "jenkins_sg_{{ jenkins_vpc.vpc.id }}"
    description: "jenkins security group for {{ jenkins_vpc.vpc.id }}"
    rules:
      - proto: tcp
        from_port: 22
        to_port: 22
        cidr_ip: 0.0.0.0/0
      # - proto: tcp
      #   from_port: 443
      #   to_port: 443
      #   cidr_ip: 0.0.0.0/0
      # - proto: tcp
      #   from_port: 80
      #   to_port: 80
      #   cidr_ip: 0.0.0.0/0
  register: jenkins_sg


- name: "Create EC2 Instance"
  amazon.aws.ec2:
    key_name: "{{ variables.ssh_key_name }}"
    state: present
    profile: "{{ variables.profile }}"
    region: "{{ variables.aws_region }}"
    group: "{{ jenkins_sg.group_name }}"
    instance_type: t2.micro
    image: "{{ variables.image }}"
    wait: yes
    instance_initiated_shutdown_behavior: terminate
    assign_public_ip: yes
    vpc_subnet_id: "{{ jenkins_vpc_subnets.results[0].subnet.id }}"
    volumes:
      - device_name: /dev/sdb
        volume_size: 20
        delete_on_termination: true
    instance_tags:
        Name: jenkinsec2
  register: newinstance